### ISSUE TITLE
Upload the model weights

### ISSUE THREAD

**Issue by CNDOTA** [YichengLin-lab/ultramutate#1]
Dear authors, congratulations on your very nice work!

I tried to run your method but found the model weight files are empty.

Could you upload the model weight files such as "PPO_reinforce_results/rl_nets/rl_net_trained.pt"?

Thank you very much!

**Comment by CNDOTA** [comment]
I found it in the raw file.

**Comment by viplovearora** [comment]
I am trying to obtain the model weights using git lfs, but I cannot download them. I am getting the following error:

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. 

Could you please fix this? Thanks!
